"""
Alaafia Complete Outcome Map — All Files
162 outcomes across IR, KR, HR, GR, CR files from NDHS 2024

Generated by merging:
- outcome_map.py (IR — 44 outcomes)
- outcome_map_KR.py (KR — 28 outcomes)  
- outcome_map_HR.py (HR — 26 outcomes)
- outcome_map_GR.py (GR — 34 outcomes)
- outcome_map_CR.py (CR — 30 outcomes)

Author: Anthonio Oladimeji
"""

import sys
sys.path.append('/Users/theoneglobal/epicause_ng')

# Import all five maps
exec(open('/Users/theoneglobal/epicause_ng/utils/outcome_map.py').read())
exec(open('/Users/theoneglobal/epicause_ng/utils/outcome_map_KR.py').read())
exec(open('/Users/theoneglobal/epicause_ng/utils/outcome_map_HR.py').read())
exec(open('/Users/theoneglobal/epicause_ng/utils/outcome_map_GR.py').read())
exec(open('/Users/theoneglobal/epicause_ng/utils/outcome_map_CR.py').read())

# Merge all outcome dictionaries
COMPLETE_OUTCOME_MAP = {}
COMPLETE_OUTCOME_MAP.update(OUTCOME_MAP)
COMPLETE_OUTCOME_MAP.update(KR_OUTCOME_ADDITIONS)
COMPLETE_OUTCOME_MAP.update(HR_OUTCOME_ADDITIONS)
COMPLETE_OUTCOME_MAP.update(GR_OUTCOME_ADDITIONS)
COMPLETE_OUTCOME_MAP.update(CR_OUTCOME_ADDITIONS)

# Merge all categories
COMPLETE_CATEGORIES = {}
COMPLETE_CATEGORIES.update(OUTCOME_CATEGORIES)
COMPLETE_CATEGORIES.update(KR_NEW_CATEGORIES)
COMPLETE_CATEGORIES.update(HR_NEW_CATEGORIES)
COMPLETE_CATEGORIES.update(GR_NEW_CATEGORIES)
COMPLETE_CATEGORIES.update(CR_NEW_CATEGORIES)

# Summary by file
BY_FILE = {}
for key, val in COMPLETE_OUTCOME_MAP.items():
    f = val['file']
    if f not in BY_FILE:
        BY_FILE[f] = []
    BY_FILE[f].append(key)

if __name__ == "__main__":
    print("=== ALAAFIA COMPLETE OUTCOME MAP ===\n")
    print(f"Total outcomes: {len(COMPLETE_OUTCOME_MAP)}")
    print(f"Total categories: {len(COMPLETE_CATEGORIES)}\n")

    print("By file:")
    for f, outcomes in BY_FILE.items():
        print(f"  {f}: {len(outcomes)} outcomes")

    print("\nBy category:")
    for cat, outcomes in COMPLETE_CATEGORIES.items():
        print(f"  {cat}: {len(outcomes)} outcomes")

    print("\nAll outcomes:")
    for key, val in COMPLETE_OUTCOME_MAP.items():
        print(f"  [{val['file']}] {val['label']} ({val['coverage_pct']}%)")
